### ISSUE TITLE
Liftover returning only column headings

### ISSUE THREAD

**Issue by halkelchen** [Cloufield/gwaslab#100]
Hi, 
I am having an issue with the lift-over function, it is just returning the column headings without any data. Any ideas what I am doing wrong or how to fix this?

<img width="958" alt="Screenshot 2024-06-13 at 10 27 31 PM" src="https://github.com/Cloufield/gwaslab/assets/162223424/6a07e0c5-b6b4-42a6-a56a-af578d32ac31">

**Comment by Cloufield** [comment]
Hi, 
it seems that mysumstats was already empty before liftover based on the log. I am wondering which function you used before liftover?

**Comment by halkelchen** [comment]
I had put it right after importing it. I moved it in my code to be after the basic check and it worked fine then, I think it must have been an error with the chromosome column before fixing it with the check. I got it to work now!
