### ISSUE TITLE
adjust y axis to be equal in miami plot

### ISSUE THREAD

**Issue by lvilarribo9** [Cloufield/gwaslab#105]
Hello!

I want to create a miami plot using to different sumstats. In the resulting figure the top and the lower manhattan plot have different y axis scales. I was wondering if there is a way to adjust the axis for both plots do they have the same scale. Here is the figure for your reference: 
![AUDIT_total_female_male_miami_plot](https://github.com/user-attachments/assets/7504141d-0ade-4534-91e1-53cec8541487)

Thanks!

**Comment by Cloufield** [comment]
Hi,

You can manually set y tick labels using `ylabels` to make y axes at the same scale:

Example:
`gl.plot_miami2(path1= gl1,
                         path2 = gl2,
                         ylabels=[10,20,30,40,50],
                         anno="GENENAME",
                         build="19"
)`

![image](https://github.com/user-attachments/assets/c394689a-06b8-485b-b35d-990cdac83343)

**Comment by lvilarribo9** [comment]
This worked, thank you very much!
