### ISSUE TITLE
Lead SNP not found in reference

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#108]
Hi Yunye,

I am making regional plot but got the issue "Lead SNP not found in reference". And the plot doesn't have LD information. I checked the script while not able to find the reason. Would you be able to offer any guidance or suggestions on how to resolve this issue? 

Best, Chenyang

```
# Lead SNP: 2:127135234:C:T, This variant is in 1kg_eur_hg38 ref data
AB42_Jigyasha.plot_mqq(mode="r",region=(chr,floor,ceiling),
                    build="38",vcf_path=gl.get_path("1kg_eur_hg38"))
AB42_Jigyasha.data
```
<img width="822" alt="image" src="https://github.com/user-attachments/assets/8f892596-244c-4e7f-b702-f2313e65464d">

> '/Users/jiangxiaofan/.gwaslab/EUR.ALL.split_norm_af.1kg_30x.hg38.vcf.gz'
> Wed Sep 25 11:40:07 2024 Start to plot manhattan/qq plot with the following basic settings:
> Wed Sep 25 11:40:07 2024  -Genome-wide significance level is set to 5e-08 ...
> Wed Sep 25 11:40:07 2024  -Raw input contains 7345561 variants...
> Wed Sep 25 11:40:07 2024  -Plot layout mode is : r
> Wed Sep 25 11:40:07 2024  -Region to plot : chr2:126885234-127385234.
> Wed Sep 25 11:40:08 2024  -Extract SNPs in region : chr2:126885234-127385234...
> Wed Sep 25 11:40:14 2024  -Extract SNPs in specified regions: 1552
> Wed Sep 25 11:40:14 2024 Finished loading specified columns from the sumstats.
> Wed Sep 25 11:40:14 2024 Start conversion and sanity check:
> Wed Sep 25 11:40:14 2024  -Removed 0 variants with nan in CHR or POS column ...
> Wed Sep 25 11:40:14 2024  -Removed 0 variants with nan in P column ...
> Wed Sep 25 11:40:14 2024  -Sanity check after conversion: 0 variants with P value outside of (0,1] will be removed...
> Wed Sep 25 11:40:14 2024  -sumstats P values are being converted to -log10(P)...
> Wed Sep 25 11:40:14 2024  -Sanity check: 0 na/inf/-inf variants will be removed...
> Wed Sep 25 11:40:14 2024  -Maximum -log10(P) values is 8.081288334617678 .
> Wed Sep 25 11:40:14 2024 Finished data conversion and sanity check.
> Wed Sep 25 11:40:14 2024 Start to load reference genotype...
> Wed Sep 25 11:40:14 2024  -reference vcf path : [/Users/jiangxiaofan/.gwaslab/EUR.ALL.split_norm_af.1kg_30x.hg38.vcf.gz](https://file+.vscode-resource.vscode-cdn.net/Users/jiangxiaofan/.gwaslab/EUR.ALL.split_norm_af.1kg_30x.hg38.vcf.gz)
> Wed Sep 25 11:40:14 2024  -Warning: no data was retrieved. Skipping ...
> Wed Sep 25 11:40:14 2024  -Retrieving index...
> Wed Sep 25 11:40:14 2024  -Ref variants in the region: 0
> Wed Sep 25 11:40:14 2024  -Lead SNP not found in reference...
> Wed Sep 25 11:40:14 2024 Finished loading reference genotype successfully!
> Wed Sep 25 11:40:14 2024 Start to create manhattan plot with 1552 variants:
> Wed Sep 25 11:40:15 2024  -Loading gtf files from:default
> INFO:root:Extracted GTF attributes: ['gene_id', 'gene_name', 'gene_biotype']
> Wed Sep 25 11:41:16 2024  -plotting gene track..
> Wed Sep 25 11:41:16 2024  -Finished plotting gene track..
> Wed Sep 25 11:41:17 2024  -Found 1 significant variants with a sliding window size of 500 kb...
> Wed Sep 25 11:41:17 2024 Finished creating Manhattan plot successfully!
> Wed Sep 25 11:41:17 2024  -Skip annotating

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/3a1e302e-0e44-4cef-a250-dd48f7459c8b">

**Comment by chenyangjjj** [comment]
Besides, when I specify the region_ref argument myself, I got **error meesage** "TypeError: mqqplot() got an unexpected keyword argument 'region_ref'"

`AB42_Jansen.plot_mqq(mode="r",region=(chr,floor,ceiling),build="38",vcf_path=gl.get_path("1kg_eur_hg38"),region_ref = ["rs12238997"])`

**Comment by Cloufield** [comment]
Hi, 
And it seems that you are using an old version? Probably updating to the latest version would sovle the problem.
I think maybe the VCF does not contain any variants in this region, or maybe the chr variable in region=(chr,floor,ceiling) is not integer. Please also try redownloading the file and check if the file is complete or not.  `gl.download_ref("1kg_eur_hg38")`

**Comment by chenyangjjj** [comment]
> Hi, It seems that you are using an old version? Probably updating to the latest version would sovle the problem. And I think maybe the VCF does not contain any variants in this region, or maybe the chr variable in region=(chr,floor,ceiling) is not integer. Please also try redownloading the file and check if the file is complete or not. `gl.download_ref("1kg_eur_hg38")`

Thank you! The updated version works now!
