### ISSUE TITLE
how to increase variant size for regional plot

### ISSUE THREAD

**Issue by ryshi06** [Cloufield/gwaslab#113]
Hi, 

Thank you for having this incredible python package. I am a R person but I found this package is fantastic for visualizing the GWAS output.

I was trying to make regional plots with the function `plot_mqq`, however, I cannot increase the marker size in the plot even after playing around with the `marker_size` parameter. 

Below is the actual command I am using:

```
zSUVr.plot_mqq(mode="r",
               region=(5,80506888-500000,80506888+500000),
               build="38",
               vcf_path=gl.get_path("1kg_eur_hg38"),
               cbar_fontsize = 15,
               fontsize = 20,
               font_family="Arial",
               anno_fontsize = 20,
               marker_size=(10,20),
               track_fontsize_ratio=1.5,
               track_exon_ratio=1,
               track_text_offset=1.5,
              #title
               title="rs112844257",
              title_fontsize=25)
plt.savefig('zSUVr_rs112844257_regional_plot.png', format='png', dpi=400, bbox_inches='tight')
```

Can you please help me on this? Thank you!

Best,
Ruyu

**Comment by ryshi06** [comment]
Thank you so much for the really quick reply!

I tried with (100,200) but still the point size is small. Should I increase the number more? Also, I am curious which command to change to make the top right corner annotation the same in your example? Thanks!

![zSUVr_rs961824652_1_205997770_regional_plot](https://github.com/user-attachments/assets/dd912c3e-8e0a-4072-9525-a5ca9be5c018)

**Comment by Cloufield** [comment]
I guess probably you are using a previous version. Would you please try the latest version v3.5.0. 

`pip install gwaslab==3.5.0`.

**Comment by ryshi06** [comment]
Yes, the version I am using now is 3.4.0. I just updated it and the size changes! Thank you for the help.
