### ISSUE TITLE
gl.Sumstats.estimate_h2_by_ldsc and other LDSC functions can't use rsID columns

### ISSUE THREAD

**Issue by igumnov-daniel** [Cloufield/gwaslab#115]
`gethapmap3` function is ran with `how='right'` arguments, but to use rsID columns it requires `how='inner'`. The only option is to change the source code locally.

**Comment by Cloufield** [comment]
Hi Daniel,
Thanks for reporting the bug. 
I have fixed this in the latest commit, which will be updated in the next version.
