### ISSUE TITLE
Unable to save stratified qq plot

### ISSUE THREAD

**Issue by Sandyyy123** [Cloufield/gwaslab#119]
Hi,

As soon as I insert stratified=True in the mode qqm, the plot is not getting saved. The command works perfectly without stratified=True. I also checked for the presence of the EAS column, and it is there.

I get the output in the window saying:

Finished creating QQ plot successfully!
Finished creating MQQ plot successfully!
Start to save figure...

But the output ends after that.

Below is the command used:
 
  # Create the plot
        mysumstats.plot_mqq(
            mode="qqm",
            anno=True,
            stratified=True,
            highlight_windowkb=1000,
            anno_set=snp_list,
            pinpoint=snp_list,
            cut=cut,
            highlight=highlight_snps,
            anno_alias=anno_alias,
	    save=f"/Manhattan_{pheno_code}_qqplot.png",
            save_args={"dpi": 300}
        )
Thanks for your help.

**Comment by Cloufield** [comment]
Hi,
I tested your script and it also stopped after `Start to save figure...`
It seems that the path you are using is `save=f"/Manhattan_{pheno_code}_qqplot.png"`, which will save the figure to root directory `/`. And this will usually cause a permission error like `PermissionError: [Errno 13] Permission denied: '/Manhattan_pheno_code_qqplot.png'`.  
I am wondering if you also had this error and would you please try again using other paths for saving like `save=f"./Manhattan_{pheno_code}_qqplot.png"` (add a dot to indicate the current directory)?

**Comment by Cloufield** [comment]
Oh, I see. Would please share the python and gwaslab version you are using? Thanks!

**Comment by Cloufield** [comment]
Hi, 
I tested with the same settings but it worked well on my machine, and here is the log. 
But I noticed that it took quite a while to save plots without setting skip when dpi is high, 
especially when you have many variants (like >10M). 

- 2min30s for 12m variants when stratified=True
- 1min30s for 12m variants without stratified=True

I guess it was just taking too long to create the plot compared to a non-stratified mqq plot. 
Could you please try lowering dpi, or add `skip=3` and see if it can create the plots?

```
2024/12/02 00:31:58 Start to create MQQ plot...v3.4.45:
2024/12/02 00:31:58  -Genomic coordinates version: 19...
2024/12/02 00:31:58  -Genome-wide significance level to plot is set to 5e-08 ...
2024/12/02 00:31:58  -Raw input contains 12557761 variants...
2024/12/02 00:31:58  -MQQ plot layout mode is : qqm
2024/12/02 00:32:00 Finished loading specified columns from the sumstats.
2024/12/02 00:32:00 Start data conversion and sanity check:
2024/12/02 00:32:00  -Sanity check will be skipped.
2024/12/02 00:32:01  -Sanity check after conversion: 0 variants with P value outside of (0,1] will be removed...
2024/12/02 00:32:02  -Sumstats P values are being converted to -log10(P)...
2024/12/02 00:32:03  -Sanity check: 0 na/inf/-inf variants will be removed...
2024/12/02 00:32:04  -Converting data above cut line...
2024/12/02 00:32:04  -Maximum -log10(P) value is 167.58838029403677 .
2024/12/02 00:32:04  -Minus log10(P) values above 20 will be shrunk with a shrinkage factor of 10...
2024/12/02 00:32:05 Finished data conversion and sanity check.
2024/12/02 00:32:05 Start to create MQQ plot with 12557761 variants...
2024/12/02 00:32:24  -Creating background plot...
2024/12/02 00:32:51 Finished creating MQQ plot successfully!
2024/12/02 00:32:51 Start to extract variants for annotation...
2024/12/02 00:32:52  -Found 89 significant variants with a sliding window size of 500 kb...
2024/12/02 00:32:52 Finished extracting variants for annotation...
2024/12/02 00:32:52 Start to process figure arts.
2024/12/02 00:32:52  -Processing X ticks...
2024/12/02 00:32:52  -Processing X labels...
2024/12/02 00:32:52  -Processing Y labels...
2024/12/02 00:32:52  -Processing Y tick lables...
2024/12/02 00:32:52  -Processing Y labels...
2024/12/02 00:32:52  -Processing lines...
2024/12/02 00:32:52 Finished processing figure arts.
2024/12/02 00:32:52 Start to annotate variants...
2024/12/02 00:32:52  -Annotating using column CHR:POS...
2024/12/02 00:32:52  -Adjusting text positions with repel_force=0.03...
2024/12/02 00:32:52 Finished annotating variants.
2024/12/02 00:32:52 Start to create QQ plot with 12557761 variants:
2024/12/02 00:32:52  -Plotting variants stratified by MAF...
2024/12/02 00:33:00  -Lambda GC (MLOG10P mode) at 0.5 is   1.21283
2024/12/02 00:33:00  -Processing Y tick lables...
2024/12/02 00:33:00 Finished creating QQ plot successfully!
2024/12/02 00:33:00 Start to save figure...
2024/12/02 00:35:35  -Saved to qqplot.png successfully! (overwrite)
2024/12/02 00:35:35 Finished saving figure...
2024/12/02 00:35:36 Finished creating plot successfully!
```

**Comment by Cloufield** [comment]
So it is due to the complexity of the plot (too many dots for matplotlib to handle for saving) as expected. 
Actually to calculate lambda, gwaslab still uses all variants. `skip` only affect whether variants are plotted or not. The annotated lamda is the still same. 
If you want all variants on the figure without setting skip or lowering dpi, I think the most simple solution is to simply wait a bit longer. If it causes memory error,  loading only the necessary columns (snpid, chrom, pos, p, eaf) for mqq plot can lower memory usage.
