### ISSUE TITLE
Miami plot

### ISSUE THREAD

**Issue by bsb2014** [Cloufield/gwaslab#122]
I generated a Miami plot, and everything looks good except for the placement of the word 'chromosome' between the Manhattan plots (see below). Is there any way to shift the text 'chromosome' slightly to the right? Thank you 

![image](https://github.com/user-attachments/assets/88cf50d4-632d-46b0-a9db-f41bbe2faffa)

**Comment by Cloufield** [comment]
Hi,
you can try adjusting `xlabel_coords=(-0.01, -0.027)` like `xlabel_coords=(-0.00,  -0.027)` to shift the text position for `plot_miami2`.

**Comment by bsb2014** [comment]
Codes are

mysumstats = gl.plot_miami/gl.plot_miami2(path1="gwas.tab1",
                           path2="gwas.tab2",
                           skip=2, 
                           cols1=["CHR","pos","Score.pval"],
                           cols2=["CHR","pos","Score.pval"],
                           titles=["test1","test2"],
                           titles_pad=[0.15,0.15],
                           anno="GENENAME", build="38",
                           region_grid=True,
                           save=True, save_args={"dpi": 300}, xlabel_coords=(-0.00,  -0.027)
                           )

plot_miami works well, but plot_miami2 does not (see the below)
##################
ax1.set_title(titles[0],y=titles_pad_adjusted[0],family=font_family)
UnboundLocalError: local variable 'titles_pad_adjusted' referenced before assignment
##################

**Comment by Cloufield** [comment]
Hi,
thanks for the feedback. I have fixed this in v3.5.4.
You could try again after updating your gwaslab version (`pip install gwaslab==3.5.4`).

**Comment by bsb2014** [comment]
It worked.
