### ISSUE TITLE
Regional plot

### ISSUE THREAD

**Issue by MC4R** [Cloufield/gwaslab#124]
Hi He,

I am trying to create a series of regional plots (up to 30) using the function `mysumstats.plot_mqq(region=(chr, start, end))`. I wanted to ask if there is any built-in function to specify multiple chromosomes for this.

Additionally, does **1kg_pan_hg19** include individuals from all ancestry groups in the 1000 Genomes Project?

Thank you.
Dev

**Comment by Cloufield** [comment]
Hi Dev,
Currently, gwaslab does not support such function. But I think you can easily do this using a for loop.
And for the second question, yes, 1kg_pan_hg19 include unrelated individuals from all ancestry groups in 1KG.

**Comment by MC4R** [comment]
Thank you, He. Much appreciated. 

Best wishes,
Dev
