### ISSUE TITLE
How to filter multiallelic snps 

### ISSUE THREAD

**Issue by 1511878618** [Cloufield/gwaslab#126]
In gwaslab, this is only done by drop duplicates of POS and REF cols.

But, If the sumstats is in a small cohort or some other situations will happens:
1) SNP A is multiallelic snp but not has the another alt allele in this cohort, so, this can't be filterd

And this caused an error on LDSC ( not only in your code) after merged to sumstats and change the direction of Z values, as multiallelic not in considration of LDSC.

So, i'm wondering is there any good ideas to filter multiallelic snp?

**Comment by Cloufield** [comment]
Hi,
gwaslab can filter multiallelic snps by using CHR:POS, SNPID, or rsID. 
I think what you mentioned is to exclude multiallelic snps when the sumstats only include one of the multiple alternative alleles?  
For now I haven't implemented any functions to do such filtering.  You may need to manually filter out thouse variant based on the genotype files you have /or 1KG. 
I will think if it is feasible to implement a filterer for multiallelic vairants using a reference file.

**Comment by 1511878618** [comment]
> Hi, gwaslab can filter multiallelic snps by using CHR:POS, SNPID, or rsID. I think what you mentioned is to exclude multiallelic snps when the sumstats only include one of the multiple alternative alleles? For now I haven't implemented any functions to do such filtering. You may need to manually filter out thouse variant based on the genotype files you have /or 1KG. I will think if it is feasible to implement a filterer for multiallelic vairants using a reference file.

That would be fatastic, if you can add that features! 👍
