### ISSUE TITLE
chrX Manhattan plot issue

### ISSUE THREAD

**Issue by michaelofrancis** [Cloufield/gwaslab#19]
Hi Cloufield, I ran into another issue with chrX. When I plot chrX by itself the plot looks like this:

<img width="1658" alt="image" src="https://github.com/Cloufield/gwaslab/assets/51752343/8037cf87-db8c-48ae-a700-98f31a78e957">

This looks correct. However, I take this same table and append it to the table with autosomes, now the plot looks like this:
<img width="1662" alt="image" src="https://github.com/Cloufield/gwaslab/assets/51752343/73c5276d-1dac-47d8-afda-17bb378fd1e5">

The centromere is no longer visible and there are some stray points at the right end that do not appear in the plot of just this chromosome.

Thanks.

**Comment by Cloufield** [comment]
Hi, 
Thanks for your question. gwaslab simply converts X to 23 when creating Manhattan plot. And honestly I am not sure what could cause this.

Could you please show the script you used and idealy an example of the POS of those stray points, to see if there are any errors during appending X to the main dataset? The raw data is stored in `sumstats.data`, which is just a pandas dataframe, you can access your data there. Thanks.

(Based on my personal experience, sometimes the data type for POS may not match between datasets, and also errors in liftover could also cause problems like this.)

**Comment by Cloufield** [comment]
BTW, the reason why the centromere disappeared is simply that centromeres are just too short to show in the Manhattan plot like that. The dots just cover the gap for centromere. I guess if you use very small marker size, you may see the centromere.

**Comment by Cloufield** [comment]
You can send the logs to this gwaslab email: gwaslab@gmail.com

**Comment by michaelofrancis** [comment]
Hey, in the process of creating the reprex I seem to have found it was a data issue on my end. Thanks, sorry.
