### ISSUE TITLE
Annotate suggestive SNPs

### ISSUE THREAD

**Issue by XaviFar** [Cloufield/gwaslab#20]
Hello,

I am currently using the 3.4.12 version, and for a given set of sumstats I wanted to create a plot annotating the genes relaxing a bit the classical GWAS threshold but it skips the annotation part, is there a way to force the annotation to annotate SNPs surpassing the significance level you have established?

```
mysumstats.plot_mqq(
                  mode="qqm",
                  anno = 'GENENAME',
                  anno_style="expand",
                  build='19',
                  marker_size=(5,10),
                  sig_level=1e-6,
                  figargs={"figsize":(15,5),"dpi":300},
                  save=f"../3-GWAS/plots/{trait}_1e6.png")
```

Thank you for this useful tool!

**Comment by Cloufield** [comment]
Hi, 
Thanks for your question. I just checked and there seems to be a small error that causes the skipping. I will revise this in the next version. 

But for the current version, you can try using `sig_level=1e-6,  sig_level_lead=1e-6` to set the threshold for extracting lead variants, and then use `suggestive_sig_line=True, suggestive_sig_level=1e-8,` to add the genome-wide significance line.  

```
mysumstats.plot_mqq(region=(1,0,100000000),skip=3, build="19",
                    sig_level=1e-6,  sig_level_lead=1e-6,  sig_line=True, sig_line_color="grey",
                    suggestive_sig_level=1e-8, suggestive_sig_line=True,  suggestive_sig_line_color="red",
                    , anno = 'GENENAME',anno_style="expand")
```
![image](https://github.com/Cloufield/gwaslab/assets/40289485/a83072f4-39e6-4209-9a29-5b9fb58fb16e)
