### ISSUE TITLE
m="qq" not working

### ISSUE THREAD

**Issue by michaelofrancis** [Cloufield/gwaslab#26]
Hi Cloufield,

Hope you're great. I ran into an issue where plotting with m="qq" doesn't work while plotting m="mqq" on the exact same data works. Here is the error log for m="qq"

Wed Jun 21 15:40:26 2023 Start to plot manhattan/qq plot with the following basic settings:
Wed Jun 21 15:40:26 2023  -Genomic coordinates version:38...
Wed Jun 21 15:40:26 2023  -Genome-wide significance level is set to 5e-08 ...
Wed Jun 21 15:40:26 2023  -Raw input contains 12587891 variants...
Wed Jun 21 15:40:26 2023  -Plot layout mode is : qq
Wed Jun 21 15:40:36 2023 Finished loading specified columns from the sumstats.
Wed Jun 21 15:40:36 2023 Start conversion and sanity check:
Wed Jun 21 15:40:38 2023  -Removed 0 variants with nan in P column ...
Wed Jun 21 15:40:38 2023  -P values are already converted to -log10(P)!

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[69], line 1
----> 1 EUR.plot_mqq(mode="qq",
      2                     scaled=True,
      3                     marker_size=(3,3),
      4                     build='38',
      5                     sc_linewidth=1,
      6                     xpad=0.01,
      7                     #highlight=h,
      8                     #highlight_windowkb =50,
      9                     figargs={"figsize":(10,10),"dpi":600},
     10                     save="EUR.qq.png",
     11                     saveargs={"dpi":600,"facecolor":"white"},
     12                     fontsize=10.8,
     13                     font_family="Arial")

File /group/tools/Anaconda/Anaconda3-2022.10/envs/R_422/lib/python3.11/site-packages/gwaslab/Sumstats.py:459, in Sumstats.plot_mqq(self, build, **args)
    456 if build is None:
    457     build = self.meta["gwaslab"]["genome_build"]
--> 459 plot = mqqplot(self.data,
    460                snpid=snpid, 
    461                chrom=chrom, 
    462                pos=pos, 
    463                p=p, 
    464                eaf=eaf,
    465                build = build, 
    466                **args)
    468 return plot

File /group/tools/Anaconda/Anaconda3-2022.10/envs/R_422/lib/python3.11/site-packages/gwaslab/mqqplot.py:508, in mqqplot(insumstats, chrom, pos, p, snpid, eaf, ea, nea, chr_dict, xtick_chr_dict, vcf_path, vcf_chr_dict, gtf_path, gtf_chr_dict, gtf_gene_name, rr_path, rr_header_dict, rr_chr_dict, rr_lim, mlog10p, scaled, mode, scatter_kwargs, qq_scatter_kwargs, qq_line_color, region, region_ref, region_ref2, region_step, region_grid, region_grid_line, region_lead_grid, region_lead_grid_line, region_hspace, region_ld_threshold, region_ld_colors, region_ld_colors1, region_ld_colors2, region_recombination, region_protein_coding, region_flank_factor, region_anno_bbox_args, taf, tabix, mqqratio, bwindowsizekb, density_color, density_range, density_trange, density_threshold, density_tpalette, density_palette, windowsizekb, anno, anno_set, anno_alias, anno_d, anno_args, anno_style, anno_fixed_arm_length, anno_source, anno_adjust, anno_max_iter, arm_offset, arm_scale, arm_scale_d, cut, skip, ystep, ylabels, ytick3, cutfactor, cut_line_color, cut_log, jagged, jagged_len, jagged_wid, sig_line, sig_level, sig_level_lead, sig_line_color, suggestive_sig_line, suggestive_sig_level, suggestive_sig_line_color, additional_line, additional_line_color, sc_linewidth, highlight, highlight_color, highlight_windowkb, highlight_anno_args, pinpoint, pinpoint_color, stratified, maf_bins, maf_bin_colors, gc, include_chrXYMT, ylim, xpad, chrpad, drop_chr_start, title, mtitle, qtitle, title_pad, title_fontsize, fontsize, font_family, anno_fontsize, figargs, colors, marker_size, use_rank, verbose, repel_force, build, dpi, save, saveargs, _invert, log)
    505     sumstats = _quick_fix_mlog10p(sumstats, scaled=scaled, verbose=verbose, log=log)
    507 # raw p for calculate lambda
--> 508 p_toplot_raw = sumstats[["CHR","scaled_P"]].copy()
    510 # filter out variants with -log10p < skip
    511 sumstats = sumstats.loc[sumstats["scaled_P"]>=skip,:]

File /group/tools/Anaconda/Anaconda3-2022.10/envs/R_422/lib/python3.11/site-packages/pandas/core/frame.py:3813, in DataFrame.__getitem__(self, key)
   3811     if is_iterator(key):
   3812         key = list(key)
-> 3813     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3815 # take() does not accept boolean indexers
   3816 if getattr(indexer, "dtype", None) == bool:

File /group/tools/Anaconda/Anaconda3-2022.10/envs/R_422/lib/python3.11/site-packages/pandas/core/indexes/base.py:6070, in Index._get_indexer_strict(self, key, axis_name)
   6067 else:
   6068     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6070 self._raise_if_missing(keyarr, indexer, axis_name)
   6072 keyarr = self.take(indexer)
   6073 if isinstance(key, Index):
   6074     # GH 42790 - Preserve name from an Index

File /group/tools/Anaconda/Anaconda3-2022.10/envs/R_422/lib/python3.11/site-packages/pandas/core/indexes/base.py:6133, in Index._raise_if_missing(self, key, indexer, axis_name)
   6130     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6132 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6133 raise KeyError(f"{not_found} not in index")

KeyError: "['CHR'] not in index"

**Comment by Cloufield** [comment]
Hi,
Sorry for the bug. It has been fixed in v3.4.16.

**Comment by michaelofrancis** [comment]
Works now! Thank you.
