### ISSUE TITLE
R2 threshold 

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#28]
Hi Yunye,

Thanks for providing such a concise package.
I am extracting the lead SNPs with mysumstats.get_lead. What is the default R2 threshold inside this function?

Best, Chenyang

**Comment by Cloufield** [comment]
Hi, Chenyang,
Thanks for your question.
get_lead() is simply based on physical positions (sliding window). https://cloufield.github.io/gwaslab/ExtractLead/
LD was not taken into account for this function.

**Comment by chenyangjjj** [comment]
Thanks for your reply! It is a different strategy from plink. Would you mind sharing some insights about this new definition? Does it performs same or better than commonly used one. any literature would also welcome, much appreciated!

**Comment by Cloufield** [comment]
Hi, 
The aim of this function is simply to check significant loci and get lead variants (the variant with the lowest P value for each locus). It is different from the idea of clumping in PLINK. You can also check the definition in this paper. Zhou, W., Kanai, M., Wu, K. H. H., Rasheed, H., Tsuo, K., Hirbo, J. B., ... & Study, C. O. H. (2022). Global Biobank Meta-analysis Initiative: Powering genetic discovery across human disease. Cell Genomics, 2(10), 100192.

**Comment by chenyangjjj** [comment]
Thanks for clarifying it!
