### ISSUE TITLE
Regional Plot missing gene data

### ISSUE THREAD

**Issue by XaviFar** [Cloufield/gwaslab#29]
I updated to the latest version 3.4.15 and suddenly the regional plots are not showing the genes.

`mysumstats.plot_mqq(mode="r", region=(10,86931726,88931726),region_grid=True, save='regional.png')`

This used to return a plot with the genes below, and now the gene information doesn't appear

**Comment by Cloufield** [comment]
Hi，
The genome version needs to be explicitly specified from 3.4.15 (because some users may forget to set this and use the wrong build). You can simply add `build="19"` or `build="38"` in plot_mqq().

**Comment by XaviFar** [comment]
Thank you! I wasn't aware of this change! It works as intended again! :) Maybe you could add some kind of warning if the build is not specified or use one by default and show it in the log. 
Again very useful tool!
