### ISSUE TITLE
Miami plot issue

### ISSUE THREAD

**Issue by soumickmj** [Cloufield/gwaslab#36]
Hi,
I'm having a strange issue with the miami plot.
![output](https://github.com/Cloufield/gwaslab/assets/20525305/99f91555-2602-44c3-b1e7-ffb9f45ecb32)
I got the miami plot.
And here's the original manhatten plot for the exact same sumstats as the top part of the miami plot:
![combo_qckMrgIgnrPLrThn2_mqq](https://github.com/Cloufield/gwaslab/assets/20525305/53f12ca5-39e4-49d6-9746-e1a0806c8b12)
Not sure why with the exact same sumstats, I'm getting different plots.

Here's my code:
gl.plot_miami(path1=df1, path2=df2, 
              cols1=['CHROM','GENPOS','LOG10P'], 
              cols2=['CHROM','GENPOS','LOG10P'], 
                scaled=True, sig_level=5e-8, sig_line_color="blue",
                # suggestive_sig_line=True, 
                suggestive_sig_level=5e-8/128, 
                skip=2, anno="GENENAME", build="19", verbose=False)

df1 and df2 are pandas dataframes.
For plotting the MQQ, I did send the dataframes to sumstats constructor
stats = gl.Sumstats(df, fmt="regenie", verbose=False)
and then plotted the mqq normally.

I tired to start with the sumstats object for the miami plot, but then it did not contain CHROM and GENPOS, rather contained the SNPIDs in the data - so the plotting function was complaining. 

Moreover, I would like to have the same Bonferroni line in the maiami as well.

Am I doing something wrong?

Thank you so much for your help :=

**Comment by soumickmj** [comment]
Thank you so much for your continous support :)

**Comment by Cloufield** [comment]
Hi,
The bug is fixed in v3.4.18.
You can also add  "additional_line=[5e-10], additional_line_color=["red"]" to add additional lines.

```
gl.plot_miami(path1=sumstats1.filter_value("P<0.0001"),
                           path2=sumstats2.filter_value("P<0.0001"),
                           cols1=["CHR","POS","P"],
                           cols2=["CHR","POS","P"],
                           titles=["bmi male","bmi female"],
                           titles_pad=[0.15,0.0],
                           skip=4,
                           anno="GENENAME",
                           region_grid=True,
                           highlight1=[(5,124289158)],
                           additional_line=[5e-10],
                           additional_line_color=["red"]
                           )
```

![image](https://github.com/Cloufield/gwaslab/assets/40289485/e689d74e-9f7a-4244-8e0a-f8dbac3e98eb)

**Comment by soumickmj** [comment]
Thank you so much :)
It's working perfectly for me!

**Comment by soumickmj** [comment]
Sorry, found a different issue.
Just like the MQQ plot, when I'm trying to annotate using a custom column, instead of GENENAME, when I'm using SNPID or any custom column, it's not working. I have added the SNPID column or the custom column to the cols1 and cols2 lists.

I'm getting the following error:

/scratch/soumick.chatterjee/conda_envs/BeegFSTorchHTBeta2/lib/python3.10/site-packages/gwaslab/annotateplot.py:414, in annotate_pair(sumstats, anno, ax1, ax5, highlight_i, to_annotate1, to_annotate5, anno_d1, anno_d2, anno_alias1, anno_alias2, anno_style, anno_args, arm_scale, anno_max_iter, arm_scale_d, arm_offset, anno_adjust, anno_fixed_arm_length, maxy1, maxy5, fontsize, font_family, region, skip, chrom, pos, repel_force, verbose, log)
    411     else:
    412         arrowargs=dict(arrowstyle='-|>', color='grey', shrinkA=10, linewidth=0.1, relpos=(1,0.5))
--> 414 anno_to_adjust = ax.annotate(annotation_text,
    415         xy=xy,
    416         xytext=xytext,
    417         bbox=bbox_para,
    418         arrowprops=arrowargs,
    419         zorder=100,
    420         **anno_default
    421         )
    422 anno_to_adjust_list.append(anno_to_adjust) 
    423 anno_count +=1

UnboundLocalError: local variable 'annotation_text' referenced before assignment

**Comment by Cloufield** [comment]
Because gwaslab uses a different logic to create the miami plot (only CHR, POS and P are used), the annotation using a custom column hasn't been implemented yet. 
I will add compatibilty for this. It might take some time. Thanks for your patience.

**Comment by Cloufield** [comment]
Hi,
This function is added in v3.4.19.
you can add the additional column in `cols1` and `cols2`, then specify the column to annotate using `anno`, which should be a string (if the column names are the same for both sumstats), or a list of two strings (if different).
```
mysumstats = gl.plot_miami(path1=sumstats1,
                           path2=sumstats1,
                           skip=2,
                           cols1=["CHR","POS","P","SNPID"],
                           cols2=["CHR","POS","P","SNPID"],
                           titles=["bmi male","bmi female"],
                           titles_pad=[0.15,0.15],
                           anno="SNPID",
                           region_grid=True
                           )
```
![image](https://github.com/Cloufield/gwaslab/assets/40289485/2cc60674-2ee2-420b-acaf-68dda6be7c87)

**Comment by Cloufield** [comment]
By the way, I noticed that you added a bin of (0.5,1) for your MAF-stratified QQ plot. 
gwaslab will only use minor allele frequency (<0.5) for this instead of EAF.  Please check if this is what you expect.
