### ISSUE TITLE
regional plot

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#37]
Hi, I was making the regional plot with plot_mqq and example data. the script will be stuck when it goes to the "Thu Jun 29 11:56:17 2023  -reference vcf path : /Users/jiangxiaofan/.gwaslab/EAS.ALL.split_norm_af.1kgp3v5.hg19.vcf.gz" .

I have downloaded the reference VCF file. I would like to check is this a version bug or local environment issue?
<img width="749" alt="image" src="https://github.com/Cloufield/gwaslab/assets/44012383/db1f0dad-0787-4c71-9ad9-83a0d8811a2b">

Here is the command I am using that taken from the tutorial.
import gwaslab as gl
mysumstats = gl.Sumstats("/Users/jiangxiaofan/Desktop/Servers/EADB/GWASlab_analysis/Ref/t2d_bbj.txt.gz",
                         snpid="SNP",chrom="CHR",pos="POS",ea="ALT",nea="REF",neaf="Frq",beta="BETA",
                         se="SE",p="P",direction="Dir",n="N",sep="\t")
mysumstats.plot_mqq(mode="r",region=(7,126253550,128253550),
                    region_grid=True,anno=True,
                    anno_args={"rotation":0,"fontsize":12},
                    vcf_path=gl.get_path("1kg_eas_hg19"))`

**Comment by Cloufield** [comment]
Hi,
Thanks for the question. I am wondering if you installed tabix (http://www.htslib.org/download/) in your environment path?
If not, gwaslab will simply scan through the vcf, which takes a very long time. 
If tabix is available in environment path, it will use .tbi to directly extract the specified region.

**Comment by chenyangjjj** [comment]
Yes, I believe that's the reason. It finished after waiting over 10mins.
Thank you!
