### ISSUE TITLE
Output exceeds the [size limit]

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#38]
Hi, I got the error about making regional locus plot. I am not able to save the regional figure. The below is my code, And is there any arguments for figure units? 

Best,Chenyang

sum_AD.plot_mqq(mode="r",region=(8,145058607,145258607),
                    build="19",region_grid=True,anno=True,anno_args={"rotation":0,"fontsize":12},
                    vcf_path=gl.get_path("1kg_eas_hg19"),
                    mtitle="AD_rs34173062 chr8:145158607",
                    save="/Users/jiangxiaofan/Desktop/GWASlab/test.png",
                    saveargs={"dpi":300,"facecolor":"white"})

error:
Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?e6a866cc-0c22-4ab0-9dab-35597ea30d1f)---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[3], line 2
      1 # AD_rs34173062 8:145158607
----> 2 sum_AD.plot_mqq(mode="r",region=(8,145058607,145258607),
      3                     build="19",region_grid=True,anno=True,anno_args={"rotation":0,"fontsize":12},
      4                     vcf_path=gl.get_path("1kg_eas_hg19"),
      5                     mtitle="AD_rs34173062 chr8:145158607",
      6                     save="[/Users/jiangxiaofan/Desktop/GWASlab/Manhattan_lh_rh_new.png](https://file+.vscode-resource.vscode-cdn.net/Users/jiangxiaofan/Desktop/GWASlab/Manhattan_lh_rh_new.png)",
      7                     saveargs={"dpi":300,"facecolor":"white"})
      9 # Hippocampus_rs34173062 8:145158607
     12 sum_Hipp_lh.plot_mqq(mode="r",region=(8,145058607,145258607),
     13                     build="19",region_grid=True,anno=True,anno_args={"rotation":0,"fontsize":12},
     14                     vcf_path=gl.get_path("1kg_eas_hg19"),
     15                     mtitle="AD_rs34173062 chr8:145158607",
     16                     save="[/Users/jiangxiaofan/Desktop/GWASlab/Manhattan_lh_rh_new.png](https://file+.vscode-resource.vscode-cdn.net/Users/jiangxiaofan/Desktop/GWASlab/Manhattan_lh_rh_new.png)",
     17                     saveargs={"dpi":300,"facecolor":"white"})

File [~/Downloads/python/lib/python3.10/site-packages/gwaslab/Sumstats.py:460](https://file+.vscode-resource.vscode-cdn.net/Users/jiangxiaofan/Desktop/~/Downloads/python/lib/python3.10/site-packages/gwaslab/Sumstats.py:460), in Sumstats.plot_mqq(self, build, **args)
    457 if build is None:
    458     build = self.meta["gwaslab"]["genome_build"]
--> 460 plot = mqqplot(self.data,
    461                snpid=snpid, 
    462                chrom=chrom, 
    463                pos=pos, 
...
-> 2428         fp = builtins.open(filename, "w+b")
   2430 try:
   2431     save_handler(self, fp, filename)

FileNotFoundError: [Errno 2] No such file or directory: '[/Users/jiangxiaofan/Desktop/GWASlab/Manhattan_lh_rh_new.png](https://file+.vscode-resource.vscode-cdn.net/Users/jiangxiaofan/Desktop/GWASlab/Manhattan_lh_rh_new.png)'

**Comment by michaelofrancis** [comment]
mkdir /Users/jiangxiaofan/Desktop/GWASlab
?

**Comment by chenyangjjj** [comment]
Yes, that is right. kind ignored. Thanks!
