### ISSUE TITLE
regional plot 

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#39]
Hi,Yunye, I had a question about regional plot. As is shown is the below figure, I found that plot_mqq function will find lead variant (SNP X)automatically in this chunk of genome.  But I am interested in another SNP(SNP Y) not the most significant one(SNP X). How should I set the parameters in plot_mqq(), and calculate its LD relation with other SNPs in selected region. I used to do it in Locuszoom. 

<img width="1343" alt="image" src="https://github.com/Cloufield/gwaslab/assets/44012383/9d440ace-8e06-4370-a091-85ba003743d9">

**Comment by Cloufield** [comment]
Hi,
you can use `region_ref` to change the reference variant.

For example,
![image](https://github.com/Cloufield/gwaslab/assets/40289485/98a493a9-25a1-4eeb-805b-3261d9605700)

You can also use `region_ref` and  `region_ref2` to select two reference variants.

![image](https://github.com/Cloufield/gwaslab/assets/40289485/a8aba9bc-783c-4297-a5db-b3d537ebb7b5)

**Comment by Cloufield** [comment]
And please specify the genome build using `build="19"` or `build="38"`.

**Comment by chenyangjjj** [comment]
Thank you! Yunye
