### ISSUE TITLE
gl.plot_miami : "local variable 'to_annotate5' referenced before assignment"

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#43]
Hi, I am using gl.plot_miami function to plot miami plots, and want to annotate the gene name of pre-defined lead variants, But I got error like this:
<img width="1031" alt="image" src="https://github.com/Cloufield/gwaslab/assets/44012383/e1575c7e-910b-49c4-86a9-6010dcb1d6f4">

"UnboundLocalError: local variable 'to_annotate5' referenced before assignment"

The script:
```
gl.plot_miami(
          "./result.mat.csv",
          "./result.mat.csv",
          cols1=["CHR","BP","P","SNP"],
          cols2=["CHR","BP","P","SNP"],
          sep=["\t","\t"],
          anno="GENENAME",
          sig_level=5e-8,
          build="19",
          anno_set1 = ["rs57434408","rs61870529"],
          save="./result.png",saveargs={"dpi":300,"facecolor":"white"})
```

**Comment by Cloufield** [comment]
Hi,
Sorry for the error.
For Miami plot, unlike mqq plot, CHR and POS need to be specified. Also pass the header of the column for annotation to  `anno`.
For the error, I will fix it in the next version.  And you can add anno_set2 = [(0,0)] to get around the error for now.

For example:

rs57434408: chr16:31066380
rs61870529 : chr10,:126358314

```
gl.plot_miami(
          "./result.mat.csv",
          "./result.mat.csv",
          cols1=["CHR","BP","P","SNP"],
          cols2=["CHR","BP","P","SNP"],
          sep=["\t","\t"],
          anno="GENENAME",
          sig_level=5e-8,
          build="19",
          anno="SNP",
          anno_set1 = [(16, 31066380),(10,126358314)],
          anno_set2 = [(0,0)],
          save="./result.png",saveargs={"dpi":300,"facecolor":"white"})
```

**Comment by chenyangjjj** [comment]
Thank you for the help!

**Comment by chenyangjjj** [comment]
Hi, The above code seems specify anno two times, and it report errors. Actually, I want to annotate pre-defined SNPs with gene name for two separate Manhattan plots in Miami plot.

In this case, Should I specify anno as "GENENAME" or "SNP"?

And by the way, is there a page that I can find arguments explanations of each function?

**Comment by chenyangjjj** [comment]
Hi, The above code seems specify anno two times, and it report errors. Actually, I want to annotate pre-defined SNPs with gene name for two separate Manhattan plots in Miami plot.

In this case, Should I specify anno as "GENENAME" or "SNP"?

And by the way, Is there a web that I can find arguments explanations of each function? like

**Comment by Cloufield** [comment]
Oops, sorry that I copied your code but forget to delete the first anno.
if anno="SNP" is specified, "SNP" will be use to annotate. 

For GENENAME, the current version has a bug and is not available for subset annotation for now. 
I will fix this by the end of this week and let you know when I finish.
 
Thanks.

**Comment by Cloufield** [comment]
The documents are available on https://cloufield.github.io/gwaslab/MiamiPlot/. I will update the explanation for each function recently.

**Comment by Cloufield** [comment]
Hi, 
you can now annotate a pre-define set of variants with v3.4.20. Thanks for your patience.

For example:
```
gl.plot_miami(
          path1=a ,
          path2=a,
          cols1=["CHR","POS","P"],
          cols2=["CHR","POS","P"],
          sep=["\t","\t"],
          anno="GENENAME",
          sig_level=5e-8,
          build="19",
          anno_set1 = [(12,112710923),(10,104748009)],
          anno_set2 = [(13,54107352)],
          save="./result.png",saveargs={"dpi":300,"facecolor":"white"})
```

![image](https://github.com/Cloufield/gwaslab/assets/40289485/3c27d0fd-4923-4cb2-9923-7307a45b3e59)

**Comment by chenyangjjj** [comment]
Thank you so much for keep updating! It works now.
