### ISSUE TITLE
Different highlight lists and colors

### ISSUE THREAD

**Issue by swvanderlaan** [Cloufield/gwaslab#50]
This is somewhat related to the other [highlight-issue](https://github.com/Cloufield/gwaslab/issues/1).

We can highlight a list of variants. Sometimes you want to highlight those that are novel, and those that are known. Essentially you'd have two lists, and therefore you'd like to use two different colors. Could this be added as an enhancement?

**Comment by Cloufield** [comment]
Hi, 
thanks for the suggestion. I am working on it (almost finished but still need some tests). I will update this in the next version soon.
Basically, gwaslab will be able to accept a list of lists to `highlight` or `pinpoint` to mark multiple sets of loci and variants.
 
Example: 
![image](https://github.com/Cloufield/gwaslab/assets/40289485/1725c102-d0f3-4546-bfd4-d4668cdb4b69)

**Comment by swvanderlaan** [comment]
Awesome! Thanks.
