### ISSUE TITLE
inferring MAF from rsid for specific population

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#53]
Hi Yunye,

There is a gwaslab enhancement suggestions:
Recently I was doing some co-localization analysis, which required MAF allele frequency. But unfortunately, many studies didn't provide it. 
Is that possible for gwaslab to include the function "inferring MAF from rsid for specific population" in the future. The solutions on the Internet is very fragmented and out of date.

That would be great if you can consider it.

Best, Chenyang

**Comment by Cloufield** [comment]
Hi, Chenyang
Thanks a lot for the suggestion. 
I think it is indeed very helpful if gwaslab can infer the allele frequency using references like VCF files with AF information. 
I will implement this soon.

**Comment by chenyangjjj** [comment]
Thanks!
