### ISSUE TITLE
issue about mqqplot anno="GENENAME"

### ISSUE THREAD

**Issue by hmutanqilong** [Cloufield/gwaslab#54]
Hi, After updating the gwaslab package to version 3.4.24, I noticed that when plotting the Manhattan plot for summary stats files and using anno="GENENAME" for annotation, the log displays "-skip annotating". I believe this may be a minor bug.

this is the log and plot:
![image](https://github.com/Cloufield/gwaslab/assets/40382784/e992fe6e-ddff-4e81-be6a-75b942b361fa)

![image](https://github.com/Cloufield/gwaslab/assets/40382784/06724c21-19e5-4f02-a6e5-41870407f989)

**Comment by Cloufield** [comment]
Hi, 
the threshold for annotation and the dashed signiifcance line is decoupled. 
You can try adding `sig_level_lead = 5e-6` to change the threshold for selecting lead variant for annotation (default is 5e-8).

**Comment by hmutanqilong** [comment]
Thanks a lot and will try it~
