### ISSUE TITLE
rsid_to_chrpos failed 

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#63]
Hi Yunye,

I used rsid_to_chrpos to assign the CHR column of data. But It failed for 99% variants. Do you know the possible reason for this

`test2 = test.data.head(10)
test2_gl = gl.Sumstats(test2,rsid="rsID",sep=",",build="38")
test2_gl.rsid_to_chrpos(path = gl.get_path("1kg_dbsnp151_hg38_auto"))`

first several rows of Input  looks like: 
  rsID | POS | STATUS
rs1268887972 | 10550 | 3899999
rs1834149098 | 10552 | 3899999
rs1834149149 | 10554 | 3899999
rs1271555979 | 10570 | 3899999
rs1207895240 | 10572 | 3899999
rs1232471101 | 10574 | 3899999
rs1275034139 | 10576 | 3899999
rs1352235814 | 10579 | 3899999
rs1191964414 | 10587 | 3899999
rs1409842294 | 10598 | 3899999

<img width="1123" alt="image" src="https://github.com/Cloufield/gwaslab/assets/44012383/512016ed-6058-4a0e-8754-afb40cfcc5a4">

first several rows of outputs  looks like: 
<img width="382" alt="image" src="https://github.com/Cloufield/gwaslab/assets/44012383/30743d14-d6ec-403d-8485-1b4ba41754d6">

**Comment by Cloufield** [comment]
Hi 
The conversion table I prepared only covers the variants in 1KG datasets (~ 80M variants). 
It seems that most rsIDs in your list are not existing in 1KG datasets. 
You can check the reference file path using gl.get_path("1kg_dbsnp151_hg38_auto"). 
For assigning rsIDs not existing in 1kg, you may need to prepare a similar reference file covering the scope of your list.

**Comment by chenyangjjj** [comment]
I agree it is the reference file issue. I will try to create one for my own task. Thanks!
