### ISSUE TITLE
https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.39.gz not available now

### ISSUE THREAD

**Issue by chenyangjjj** [Cloufield/gwaslab#74]
Hi, I just found https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.39.gz is not available now, they have new Hg38 version, GCF_000001405.40.gz

**Comment by Cloufield** [comment]
Hi, 
thanks for the information. Actually GCF_000001405.40.gz has been updated in the reference file. https://github.com/Cloufield/gwaslab/blob/main/src/gwaslab/data/reference.json
