### ISSUE TITLE
scikit-allel build issues

### ISSUE THREAD

**Issue by jonathangriffiths** [Cloufield/gwaslab#78]
I'm having some challenges installing your package because the current build of scikit-allel requires a patch for which the PR hasn't yet been accepted: https://github.com/cggh/scikit-allel/pull/403

This leads to this kind of error:

```
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
```

Because your package specifies the version of scikit-allel to install, it makes it challenging to use the version supplied by the lovely nostosgenomics.

Could you give any advice on how to navigate this, if you've had these issues yourself?

Thanks!

**Comment by Cloufield** [comment]
Hi,
I haven't had this issue before when installing gwaslab or scikit-allel via pip. 
Sorry that I may not understand the situation. Could you please describe a little more about how and when you met this error? Thanks!

**Comment by jonathangriffiths** [comment]
If you've not experienced it, then no problem! It's where I've used poetry to install dependencies of my package - yours is one of those, and scikit-allel is one in turn.

It's not your problem to fix, so I'll close the issue - I just wanted to check!
