### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by michaelofrancis** [Cloufield/gwaslab#8]
Hi, thank you for this package. There are a few more issues I would like to see fixed before using this package in a manuscript. Maybe there are already ways to fix these with parameters?

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/51752343/227970845-e2505f60-a954-431e-b266-a5f207bd0120.png">

1. There are too many axis ticks below the cut, and too few above.
2. This gap before the beginning of the plot is not good
3. How to change thickness of significance line? Right now it is too thick
4. Uneven gaps between chromosomes, compare these large gaps in the later chromsomes to chr 1-12.

Thanks!

**Comment by Cloufield** [comment]
Hi,
Thanks again for your very deailed comments.
I just fixed those issues.  Please update to `pip install gwaslab==3.4.2`.
You can now use `ylabels` to set the y ticklabels and `font_family` to set the font family.
"Chromosomes" was changed to "Chromosome".

Hope this is what you expected for the figure. 
```
mysumstats.plot_mqq(mode="m", 
                    skip=2, 
                    cut=50,
                    ylabels=[5,10,20,30,40,50,100,168],
                    use_rank=True,
                    sc_linewidth=1,
                    xpad=0.01,
                    marker_size=(10,10),
                    fontsize=10,
                    font_family="Arial")
```
![image](https://user-images.githubusercontent.com/40289485/228116503-b8387fc5-f97d-4524-b751-f31cf3983635.png)

**Comment by michaelofrancis** [comment]
Hi, thanks again for your response. I think we are almost there...

I was thinking the expected behavior from "cut" was to change to logarithmic scale (technically, the log of the log scale since it is already a log scale of the original P values) , i.e. like this, where the y-axis doubles and each doubling remains the same distance apart.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/51752343/228259683-476a4f38-af6b-411c-b90f-edbf1bb27e50.png">

Unfortunately the current behavior is to "re-set" the axis but not change to log scale.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/51752343/228260074-7ae0f3d7-a413-46cd-a2a5-3354a7507074.png">

Could you possibly implement the switch to log scale? I think this option would make this plotting tool very valuable. This is the last thing I will ask, I promise :)

**Comment by Cloufield** [comment]
Hi,
You can now add "cut_log=True" to change the y axis above "cut" to log scale, and add "jagged=True" to make a jagged y axis if needed.
Please update to "pip install gwaslab==3.4.3".

```
mysumstats.plot_mqq(mode="m",skip=3,
                    cut=50,
                    cut_log=True,
                    ylabels=[10,20,30,40,50,100,200,400],
                    fontsize = 8)
```
![image](https://user-images.githubusercontent.com/40289485/228408921-6420a761-3766-4f88-9488-0a1624cf1287.png)

**Comment by michaelofrancis** [comment]
Incredible. Amazing. Thank you!!
