### ISSUE TITLE
Issue on QQ plot visualization alone

### ISSUE THREAD

**Issue by Youpu-Chen** [Cloufield/gwaslab#90]
Hi there.

Thank you for developing this great tool!
I've encountered a problem when trying to visualize the QQ plot alone.
It report:

```
AttributeError: 'NoneType' object has no attribute 'get_xlim'
```

All the pkgs I imported were:
```
import gwaslab as gl
import matplotlib.pyplot as plt

from matplotlib import rcParams
rcParams["font.family"] = "Arial" 
```

The code snippet to plot:
```
mysumstats.plot_mqq(mode="qq", 
                    # fig_args = {"figsize":(6,6)}, 
                    check=False, 
                    verbose=False)
```

The file format is PLINK 2.0.

I'll really appreciate it if you could give me a hint.

**Comment by Cloufield** [comment]
Hi Youpu,
Sorry for the bug. Actually, I have already fixed it in this [commit](https://github.com/Cloufield/gwaslab/commit/77bf251aa25a5134b34b540cbdfe59acfb7e3c4f).
Please try using the latest version ( `pip install gwaslab==3.4.43` ). Thanks!

**Comment by Youpu-Chen** [comment]
The problem was solved, Thank you!
