### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by bsb2014** [Cloufield/gwaslab#93]
pip install gwaslab==3.4.43
#############################
ERROR: Ignored the following versions that require a different python version: 3.4.25 Requires-Python <=3.9,>=3.8; 3.4.26 Requires-Python <=3.9,>=3.8; 3.4.27 Requires-Python <=3.9,>=3.8; 3.4.28 Requires-Python <=3.9,>=3.8; 3.4.29 Requires-Python <=3.9,>=3.8; 3.4.30 Requires-Python <=3.10,>=3.8; 3.4.31 Requires-Python <=3.10,>=3.8; 3.4.32 Requires-Python <=3.10,>=3.8; 3.4.33 Requires-Python <=3.10,>=3.8; 3.4.34 Requires-Python <=3.10,>=3.8; 3.4.35 Requires-Python <=3.10,>=3.8; 3.4.36 Requires-Python <=3.10,>=3.8; 3.4.37 Requires-Python <=3.10,>=3.9; 3.4.38 Requires-Python <=3.10,>=3.9; 3.4.39 Requires-Python <=3.10,>=3.9; 3.4.40 Requires-Python <=3.10,>=3.9; 3.4.41 Requires-Python <=3.10,>=3.9; 3.4.42 Requires-Python <=3.10,>=3.9; 3.4.43 Requires-Python <=3.10,>=3.9; 3.4.44 Requires-Python <=3.10,>=3.9
ERROR: Could not find a version that satisfies the requirement gwaslab==3.4.43 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 3.3.11, 3.3.12, 3.3.13, 3.3.14, 3.3.15, 3.3.16, 3.3.17, 3.3.18, 3.3.19, 3.3.20, 3.3.21, 3.3.22, 3.3.23, 3.3.24, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9, 3.4.10, 3.4.11, 3.4.12, 3.4.13, 3.4.14, 3.4.15, 3.4.16, 3.4.17, 3.4.18, 3.4.19, 3.4.20, 3.4.21, 3.4.22, 3.4.23, 3.4.24)
ERROR: No matching distribution found for gwaslab==3.4.43
################################
My python version is 

Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information

**Comment by Cloufield** [comment]
Hi,
Thanks for the feedback.
Python 3.10 should have worked. I guess the way I set the requirements was wrong.
For now, you can install it using `pip install --ignore-requires-python gwaslab==3.4.43` to skip the version check for Python.

**Comment by bsb2014** [comment]
Thanks for your prompt response. I have another problem.
ERROR: Failed building wheel for pySAM.
My pySAM version is 0.21.0

**Comment by Cloufield** [comment]
That would be a pysam installation issue. 
I also met that error several times so I restricted the version of pysam to 0.19.
Would you please try 'pysam==0.19.1'?

**Comment by Cloufield** [comment]
Sorry for not making it clear. There is no need to change that.

1. If you want to install in your current environment, I think you could simply run `pip install pysam==0.19.1` and then `pip install --ignore-requires-python gwaslab==3.4.43`. 
2. If installing by creating a new environment, you can use conda with this [environment.yml](https://github.com/Cloufield/gwaslab/blob/main/environment_3.4.40.yml) (for versions >3.4.40).

**Comment by bsb2014** [comment]
I tried the method 1 and failed.

ERROR: Failed building wheel for pysam. 

More information:  pysam/libcalignedsegment.pyx:1451:21: Invalid index type 'double'

**Comment by jmarshall** [comment]
The Cython source code in pysam ≤0.20.0 expected to be compiled with `language_level=2`. You are now compiling it with a version of Cython in which that is not the default, as indicated by that “invalid index type” error message.

The sensible way to fix this is to move forward in time by using a current version of pysam (currently 0.22.1, which is fully Python/Cython 3) rather than moving backward in time by trying to use an older pysam that predates such versions of Cython.

**Comment by Cloufield** [comment]
> The Cython source code in pysam ≤0.20.0 expected to be compiled with `language_level=2`. You are now compiling it with a version of Cython in which that is not the default, as indicated by that “invalid index type” error message.
> 
> The sensible way to fix this is to move forward in time by using a current version of pysam (currently 0.22.1, which is fully Python/Cython 3) rather than moving backward in time by trying to use an older pysam that predates such versions of Cython.

Thanks for your comments! I totally agree with your solution. Just tested and updated pysam requirements to the latest version v0.22.1.

**Comment by Cloufield** [comment]
> I tried the method 1 and failed.
> 
> ERROR: Failed building wheel for pysam.
> 
> More information: pysam/libcalignedsegment.pyx:1451:21: Invalid index type 'double'
> 
> It should be relevant to my Cython installation.

@bsb2014 ,  Would you please try 'pip install gwaslab==3.4.45'. I updated the python and pysam version requirements and it should work now.

**Comment by bsb2014** [comment]
It works!!
