### ISSUE TITLE
filter_value filters all data

### ISSUE THREAD

**Issue by lbwfff** [Cloufield/gwaslab#94]
Dear developer, 

I am trying to filter Sumstats object using filter_value but I found that no matter what I do it filters out all the rows, below is my code
![Screenshot 2024-05-27 at 1 43 38 PM](https://github.com/Cloufield/gwaslab/assets/74947198/bc9f1820-3f33-40b4-a355-706653b9bd1e)
I tried mysumstats.filter_value('CHR==1').plot_mqq() and got empty images. 
At first I thought it was the pandas version, but installing 2.2 version of pandas didn't solve the problem, how can I fix this?

Thanks,
LeeLee

**Comment by Cloufield** [comment]
Hi LeeLee,

Would you please check the data type of CHR by `mysumstats.data.dtypes`? 
Probably you need to run `mysumstats.fix_chr()` or `mysumstats.basic_check()` first, since 'CHR==1' only works if CHR is int.

**Comment by lbwfff** [comment]
Thanks! mysumstats.basic_check() solved my problem!
