### ISSUE TITLE
Effect Allele select in 2SMR

### ISSUE THREAD

**Issue by chide-org** [Cloufield/gwaslab#96]
由于我没有gwas相关经验，所以这个问题可能会看起来比较可笑，但是这确实困扰了我很久。
在进行孟德尔随机化分析的时候，gwas得到的数据中有A1和A2列，我们需要的是effect allele和other allele，但是如何确定哪一个是effect allele，这个的判断依据是什么？我看到你的文章中写道A1就是effect allele，但是没有给出解释
<img width="295" alt="image" src="https://github.com/Cloufield/gwaslab/assets/144027281/118e8808-711f-4d60-b12c-6e0956a69f9c">
让我更加疑惑的是，当我去查阅文献时，mr的文章给出的工具变量中的other allele全部是ncbi上snv的参考位点，我对比了相同的rs号，发现我的gwas数据中有几乎一半的A1是文献中的effect allele，几乎一半的A1是文献中的other allele。
我可能会由于查阅的文献很少以及对比的snp数量很少而犯错，如果是真的希望能够得到指正。
我的问题就是这样，gwas数据中如何确定effect allele，期待你的回应！

**Comment by Cloufield** [comment]
你好，
GWAS相关软件并没有统一规范A1A2如何指代effect allele和other allele，所以得具体情况具体分析（有的软件还使用A0，A1），一般只能找gwas使用的软件的文档说明，或者是sumstats附带的readme,或是来源数据库的说明来判断effect allele。

一般让初学者更困惑的是有时effect allele和other allele，与参考基因组的ref和alt并不一一对应，具体可以参考这篇文章 https://gwaslab.org/2021/08/21/allele-concept/ . 

> gwas数据中有几乎一半的A1是文献中的effect allele，几乎一半的A1是文献中的other allele

你所提到的这种情况很常见，所以在做MR时需要对多个数据集的数据进行harmonization（也就是对齐effect allele）。

**Comment by chide-org** [comment]
感谢你的耐心解答！我想我应该理解了：计算beta或or的为referrence/other allele，另外一个是effect allele。
<img width="503" alt="image" src="https://github.com/Cloufield/gwaslab/assets/144027281/d662f4ec-45a2-4da8-aeed-1bbec9cf249f">
那么依靠这个注释文件我可以确定A1是referrence/other allele，A2是effect allele
<img width="439" alt="image" src="https://github.com/Cloufield/gwaslab/assets/144027281/d29e9bf5-0ae6-4a56-ba07-fb06ad213f16">
依靠这个注释文件我可以确定A2是effect allele。


另外我还发现这两个注释文件计算频率的时候都是使用的A1，也就是我理解的referrence/other allele，而在做MR分析的时候，我了解的位点频率是eaf（effect allele frequency），所以数据中给出的频率并不是我分析所需要的eaf，我理解的是正确的吗？

- 对effect allele的理解是否正确
- 以上两份注释中的frequency是否并非eaf

我的问题就是这样，期待你的解答！

**Comment by Cloufield** [comment]
能明确的是，beta或or为effect/risk allele相对于non-effect/non-risk allele的效应。 

因为referrence allele用法很混乱，有时指基因组，有时又指回归，有时是effect allele，有时又不是，单凭借referrence allele无法判断。不需要拘泥于referrence 这个名称，重点看效应量对应的allele就行。

图一里的A1，referrence allele （相对回归来说） 是 effect allele，也就是OR指的是A1的效应。FRQ为A1的频率，所以就是EAF。
图二里的Allele1，referrence allele， 无法判断referrence allele是不是effect allele （无法确定Effect指的是哪个allele的效应）。但这个格式看起来像是METAL的输出，Allele1有可能是effect allele。可以挑显著位点与同人群的其他GWAS比较判断。

**Comment by chide-org** [comment]
感谢感谢！看来我之前的理解确实有误，计算效应值（beta，or）的才是effect allele。
我想我没有问题了，感谢你的耐心！
